"""Master Content Track — single source-of-truth for all lesson output documents.

All output documents (lesson plan, student packet, slideshow) are compiled as
views of a single ``MasterContent`` object rather than generated by separate LLM
calls.  This eliminates content drift between documents and reduces total token
usage.
"""

from __future__ import annotations

import logging

from pydantic import BaseModel, Field, field_validator

from clawed.models import DifferentiationNotes  # reuse — do not duplicate

logger = logging.getLogger(__name__)


class VocabularyEntry(BaseModel):
    """A vocabulary term with definition, context sentence, and optional image."""

    term: str
    definition: str
    context_sentence: str
    image_spec: str = ""


class PrimarySource(BaseModel):
    """A primary-source document used in instruction or station work."""

    id: str
    title: str
    source_type: str  # "text_excerpt", "political_cartoon", "map", "data_table", "photograph", "diagram"
    content_text: str
    attribution: str
    image_spec: str = ""
    scaffolding_questions: list[str] = Field(default_factory=list)

    @field_validator("image_spec", mode="after")
    @classmethod
    def require_image_spec(cls, v: str) -> str:
        if not v.strip():
            logger.warning("Empty image_spec in PrimarySource — provide a specific image search query")
        elif len(v.strip()) < 10:
            logger.warning("image_spec '%s' is too vague — use a specific search query", v)
        return v

    @field_validator("content_text", mode="after")
    @classmethod
    def require_substantive_content(cls, v: str) -> str:
        if v.strip() and len(v.strip()) < 50:
            logger.warning(
                "PrimarySource content_text is only %d chars — include the ACTUAL source text",
                len(v.strip()),
            )
        return v


class InstructionSection(BaseModel):
    """One section of the direct-instruction sequence."""

    heading: str
    content: str
    teacher_script: str
    key_points: list[str] = Field(default_factory=list)
    image_spec: str = ""
    hook: str = ""  # Opening hook — analogy, story, provocative question, character intro
    transition: str = ""  # Scripted pivot phrase to next section

    @field_validator("image_spec", mode="after")
    @classmethod
    def warn_empty_image_spec(cls, v: str) -> str:
        if not v.strip():
            logger.warning("Empty image_spec in InstructionSection — images will be missing for this section")
        return v


class GuidedNote(BaseModel):
    """A single fill-in-the-blank guided-notes item."""

    prompt: str
    answer: str
    section_ref: str


class StationDocument(BaseModel):
    """A learning-station task tied to a primary source."""

    title: str
    source_ref: str  # id of the referenced PrimarySource
    task: str
    student_directions: str
    teacher_answer_key: str
    timer_minutes: int = 10  # Visual timer for rotation
    group_roles: str = ""  # "Reader, Recorder, Reporter, Timekeeper"
    reporting_template: str = ""  # Structured output format for each station


class StimulusQuestion(BaseModel):
    """An assessment question anchored to a stimulus (text, image, data, etc.).

    Every question *must* have a non-empty stimulus — this is a hard pedagogical
    requirement enforced at validation time.
    """

    stimulus: str
    stimulus_type: str  # "text_excerpt", "image", "data", "map", "diagram", "scenario"
    stimulus_image_spec: str = ""
    question: str
    answer: str
    cognitive_level: str = ""  # "recall", "application", "analysis"
    sentence_starters: list[str] = Field(default_factory=list)  # ["According to the source, ___"]
    response_framework: str = ""  # "TEA", "RACE", "CER"

    @field_validator("stimulus", mode="before")
    @classmethod
    def _require_stimulus(cls, v: object) -> object:
        if isinstance(v, str) and not v.strip():
            raise ValueError("stimulus must not be empty — every question needs a pedagogical anchor")
        return v


class DoNow(BaseModel):
    """The lesson-opening Do Now activity."""

    stimulus: str
    stimulus_type: str
    questions: list[str]
    answers: list[str]
    hook_type: str = ""  # "analogy", "provocative_question", "real_world_scenario", "mystery", "image_analysis"


class IndependentWork(BaseModel):
    """Structured independent-practice task."""

    task: str
    rubric_snippet: str = ""
    exemplar: str = ""


class JigsawStructure(BaseModel):
    """Structured jigsaw activity with timed expert/teaching group rotations."""

    num_expert_groups: int = 4
    documents_per_group: list[str] = Field(default_factory=list)  # PrimarySource IDs
    expert_phase_minutes: int = 10
    teaching_phase_minutes: int = 10
    graphic_organizer: str = ""  # Table headers/column structure
    share_out_protocol: str = ""  # "Each expert has 2 minutes to teach..."
    debrief_question: str = ""  # Whole-class closing question


class CreativeActivity(BaseModel):
    """A creative engagement activity beyond traditional document analysis."""

    activity_type: str = ""  # role_play, debate, podcast_script, social_media, gallery_walk, mock_trial, time_travel
    title: str = ""
    scenario: str = ""  # The setup/premise students enter
    roles: list[str] = Field(default_factory=list)  # Character roles
    student_directions: str = ""  # Step-by-step what students do
    deliverable: str = ""  # What students produce
    debrief: str = ""  # How teacher wraps up
    time_minutes: int = 15


class MasterContent(BaseModel):
    """Single source-of-truth for an entire lesson.

    All output documents are compiled as views of this object.  Field names
    intentionally mirror the sections of a typical NYC/state lesson plan.
    """

    title: str
    subject: str
    grade_level: str
    topic: str
    standards: list[str] = Field(default_factory=list)
    objective: str
    duration_minutes: int = 45

    vocabulary: list[VocabularyEntry] = Field(default_factory=list)
    primary_sources: list[PrimarySource] = Field(default_factory=list)
    do_now: DoNow
    direct_instruction: list[InstructionSection]
    guided_notes: list[GuidedNote]
    stations: list[StationDocument] = Field(default_factory=list)
    independent_work: IndependentWork | None = None
    exit_ticket: list[StimulusQuestion]
    differentiation: DifferentiationNotes
    homework: str | None = None
    materials_needed: list[str] = Field(default_factory=list)

    # v4.9: Voice & structure fields
    lesson_personality: str = Field(
        default="",
        description="One-line theme/character for the lesson (e.g. 'Today we're detectives investigating...')",
    )
    minute_by_minute: list[dict] = Field(
        default_factory=list,
        description="[{'time': '0:00-3:00', 'activity': 'Do Now', 'teacher_moves': '...'}]",
    )
    jigsaw: JigsawStructure | None = Field(
        default=None,
        description="Structured jigsaw — required when lesson_format is 'jigsaw'",
    )
    creative_activity: CreativeActivity | None = Field(
        default=None,
        description="Creative engagement activity (role play, debate, podcast, etc.)",
    )

    # v4.8: Lesson format tracking for variety enforcement
    lesson_format: str = Field(
        default="document_analysis",
        description=(
            "Pedagogical format: document_analysis, station_rotation, "
            "socratic_seminar, jigsaw, gallery_walk, gradual_release, "
            "simulation, lecture_discussion"
        ),
    )

    # v4.8: Optional enrichment fields (don't break existing generation)
    misconceptions: list[str] = Field(
        default_factory=list,
        description="Common student misconceptions to watch for during this lesson",
    )
    formative_checks: list[str] = Field(
        default_factory=list,
        description="Mid-lesson check-for-understanding questions (distinct from exit ticket)",
    )
    prerequisite_skills: list[str] = Field(
        default_factory=list,
        description="Skills students should have before this lesson",
    )

    # ── backwards-compat bridge ────────────────────────────────────────────

    def to_daily_lesson(self) -> "DailyLesson":  # noqa: F821 — resolved at runtime
        """Return a legacy ``DailyLesson`` compiled from this MasterContent.

        Allows existing code that expects ``DailyLesson`` objects to continue
        working without modification while the rest of the codebase migrates to
        the Master Content Track.
        """
        from clawed.models import DailyLesson, ExitTicketQuestion

        do_now_text = self.do_now.stimulus
        if self.do_now.questions:
            do_now_text += "\n\n" + "\n".join(f"Q: {q}" for q in self.do_now.questions)

        direct_instruction_text = "\n\n".join(f"## {s.heading}\n{s.content}" for s in self.direct_instruction)

        guided_practice_text = "\n".join(f"- {n.prompt} (Answer: {n.answer})" for n in self.guided_notes)

        exit_ticket_items = [
            ExitTicketQuestion(
                question=f"{q.stimulus}\n\n{q.question}",
                expected_response=q.answer,
            )
            for q in self.exit_ticket
        ]

        return DailyLesson(
            title=self.title,
            lesson_number=1,
            objective=self.objective,
            standards=self.standards,
            do_now=do_now_text,
            direct_instruction=direct_instruction_text,
            guided_practice=guided_practice_text,
            independent_work=self.independent_work.task if self.independent_work else "",
            exit_ticket=exit_ticket_items,
            homework=self.homework or "",
            differentiation=self.differentiation,
            materials_needed=self.materials_needed,
        )
